# Generated by Django 4.1.5 on 2023-02-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_reservationordermodel_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationordermodel',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
